name: sharebridge_mobile_app
description: ShareBridge mobile app scaffold for donor setup flow.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: true
